# frozen_string_literal: true

module Fontico
  module Emitters
    # An Adafruit GFXfont, for a display driven by Adafruit_GFX or Arduino_GFX.
    # It compiles into the binary, so unlike the TTF target there is no
    # FreeType on the device, no font renderer, and no filesystem to flash.
    #
    # The trade is that a GFXfont is a fixed size and one bit deep. Ask for the
    # size you will draw at; scaling one up is what the built-in 6x8 font
    # already does badly.
    #
    # Char codes rather than codepoints, because that is what the draw path
    # takes: Adafruit_GFX and Arduino_GFX both index glyphs as `c - first` off
    # a byte. They are therefore positional, which is exactly why the codes and
    # the bitmaps are emitted into one file — they cannot fall out of step with
    # each other. What keeps them stable across builds is the order, and the
    # order comes from the append-only codepoints in icons.lock.
    class GfxFont
      # 0x20..0xFF. Below 0x20 is control characters, which some print paths
      # intercept before the font ever sees them.
      FIRST = 0x20
      LAST  = 0xFF
      CAPACITY = LAST - FIRST + 1

      def initialize(manifest, build, lock: nil, ttf: nil, size: 24, runner: nil)
        @manifest = manifest
        @build = build
        @lock = lock
        @ttf = ttf
        @size = size
        @runner = runner || NodeRunner.new
      end

      # Same rule as the font it is rasterised from: one bit cannot hold
      # colour, so a multicolour icon has nothing to become.
      def accepts?(icon) = !(@lock&.multicolor?(icon.name) || icon.multicolor?)
      def rules_only? = false

      def call
        icons = @build.map(&:first).sort_by { codepoint!(_1) }
        # A GFXfont with no glyphs is not a font. This is reachable when every
        # icon in the manifest was dropped as multicolour.
        raise Fontico::Error, "the gfxfont target has no icons left to rasterise" if icons.empty?

        guard_capacity!(icons)

        result = @runner.run("rasterize.mjs", {
                               ttf: @ttf, size: @size,
                               glyphs: icons.map { { name: _1.name, codepoint: codepoint!(_1) } }
                             })
        rows = rows_for(result["glyphs"], icons)
        guard_blank!(rows)

        render(rows, result["yAdvance"])
      end

      private

      def codepoint!(icon)
        @lock&.codepoint_for(icon.name) ||
          raise(Fontico::Error, "#{icon.name} has no codepoint in icons.lock")
      end

      def rows_for(glyphs, icons)
        by_name = glyphs.to_h { [_1["name"], _1] }
        offset = 0
        icons.each_with_index.map do |icon, i|
          g = by_name.fetch(icon.name)
          row = { name: icon.name, source: icon.source, char: FIRST + i,
                  ident: Header.identifier(icon.name), offset: offset, glyph: g }
          offset += g["bytes"].size
          row
        end
      end

      # A GFXfont has room for one byte's worth of glyphs and no more. Failing
      # here beats emitting a font that silently stops at icon 224.
      def guard_capacity!(icons)
        return if icons.size <= CAPACITY

        raise Fontico::Error,
              "the gfxfont target holds #{CAPACITY} icons (a GFXfont is indexed off a byte) " \
              "and this manifest has #{icons.size}. Split the icons across two fonts, or " \
              "build the c target instead, which addresses codepoints directly."
      end

      # An icon that rasterised to nothing would draw as empty space with no
      # complaint, on a screen nobody is watching.
      def guard_blank!(rows)
        blank = rows.select { _1[:glyph]["blank"] }
        return if blank.empty?

        raise Fontico::Error, <<~MSG
          #{blank.size} icon(s) rasterised blank at #{@size}px and would draw as nothing:

            #{blank.map { _1[:name] }.join("\n  ")}

          Thin strokes fall through a one-bit threshold at small sizes. Either
          raise the gfxfont size, or drop these from the target.
        MSG
      end

      def render(rows, y_advance)
        bytes = rows.flat_map { _1[:glyph]["bytes"] }
        tag = "fontico_icons#{@size}"

        <<~HEADER
          /* generated by fontico — do not edit.
           *
           * #{rows.size} icon(s) as an Adafruit GFXfont, rasterised at #{@size}px, one bit
           * deep. #{bytes.size} bytes of bitmap. Include this after your GFX library
           * header; it defines the GFXglyph/GFXfont structs only if that has
           * not already done so.
           *
           *   gfx->setFont(&#{tag});
           *   gfx->drawChar(x, y, #{rows.first[:ident]}, fg, bg, 1);
           *
           * The char codes below are positional, so they and the bitmaps are
           * one artifact and are regenerated together. Their order follows the
           * append-only codepoints in icons.lock, so adding an icon appends
           * rather than renumbering what is already flashed.
           */
          #ifndef FONTICO_GFXFONT_H
          #define FONTICO_GFXFONT_H

          #include <stdint.h>

          /* Adafruit_GFX's own guard, so the library wins when it is present. */
          #ifndef _GFXFONT_H_
          #define _GFXFONT_H_
          typedef struct {
            uint16_t bitmapOffset;
            uint8_t  width, height, xAdvance;
            int8_t   xOffset, yOffset;
          } GFXglyph;
          typedef struct {
            uint8_t  *bitmap;
            GFXglyph *glyph;
            uint16_t  first, last;
            uint8_t   yAdvance;
          } GFXfont;
          #endif

          #ifndef PROGMEM
          #define PROGMEM
          #endif

          #{defines(rows).join("\n")}

          /* One continuous MSB-first bitstream, no padding between rows. */
          static const uint8_t #{tag}_bitmaps[] PROGMEM = {
          #{bitmap_lines(bytes).join("\n")}
          };

          static const GFXglyph #{tag}_glyphs[] PROGMEM = {
          #{rows.map { glyph_line(_1) }.join("\n")}
          };

          static const GFXfont #{tag} PROGMEM = {
            (uint8_t *)#{tag}_bitmaps,
            (GFXglyph *)#{tag}_glyphs,
            0x#{format("%02X", FIRST)}, 0x#{format("%02X", rows.last[:char])}, #{y_advance}
          };

          #endif /* FONTICO_GFXFONT_H */
        HEADER
      end

      def defines(rows)
        width = rows.map { _1[:ident].length }.max.to_i
        rows.map do |r|
          format("#define %-#{width}s 0x%02X /* %s  %s */",
                 r[:ident], r[:char], r[:name], r[:source])
        end
      end

      def bitmap_lines(bytes)
        bytes.each_slice(16).map { "  #{_1.map { |b| format("0x%02X", b) }.join(", ")}," }
      end

      def glyph_line(row)
        g = row[:glyph]
        format("  { %5d, %3d, %3d, %3d, %4d, %4d }, /* %s */",
               row[:offset], g["width"], g["height"], g["xAdvance"],
               g["xOffset"], g["yOffset"], row[:name])
      end
    end
  end
end
