# frozen_string_literal: true

module Fontico
  module Emitters
    # A C header, so firmware names icons by intent like every other consumer.
    # The device draws them out of the TTF this is emitted alongside, and the
    # two agree because both read codepoints from icons.lock.
    #
    # That pinning matters more here than anywhere else fontico uses it. A
    # codepoint compiled into a flashed .bin cannot be hotfixed: if adding an
    # icon renumbered the others, every board in the field would start drawing
    # the wrong picture after an OTA. The lock is append-only precisely so that
    # cannot happen.
    #
    # What the firmware gets out of this, beyond the naming: the UTF-8 bytes
    # are literals decided at build time, so nothing parses "U+e63e" or
    # assembles a String on the heap inside a draw loop.
    class Header
      PREFIX = "ICON_"

      # Every byte of a private-use codepoint's UTF-8 is emitted as a \x
      # escape and nothing else follows it inside the quotes, so C's greedy
      # hex escapes have nothing extra to swallow.
      def initialize(manifest, build, lock: nil)
        @manifest = manifest
        @build = build
        @lock = lock
      end

      # A glyph carries no colour, so the same icons the font refuses are the
      # ones this cannot name — there would be no glyph at the codepoint.
      def accepts?(icon) = !(@lock&.multicolor?(icon.name) || icon.multicolor?)
      def rules_only? = false

      def self.identifier(name) = "#{PREFIX}#{name.upcase.gsub(/[^A-Z0-9]+/, "_")}"

      # U+E001 -> "\xEE\x80\x81"
      def self.utf8_literal(codepoint)
        [codepoint].pack("U").bytes.map { format("\\x%02X", _1) }.join
      end

      def call
        rows = @build.map { |icon, _| row(icon) }.sort_by { _1[:name] }
        guard_ascii!(rows)
        guard_collisions!(rows)

        <<~HEADER
          /* generated by fontico — do not edit.
           *
           * #{rows.size} icon(s) from #{File.basename(@manifest.path || "icons.yml")}, drawn out of
           * the icons.ttf built beside it. Codepoints are pinned in icons.lock
           * and never reissued, so a name compiled into a flashed image keeps
           * meaning the same picture across every later build.
           */
          #ifndef FONTICO_ICONS_H
          #define FONTICO_ICONS_H

          #include <stdint.h>

          #ifdef __cplusplus
          extern "C" {
          #endif

          #define FONTICO_ICON_COUNT #{rows.size}

          /* UTF-8 literals, ready to hand to OpenFontRender / FreeType. */
          #{defines(rows).join("\n")}

          typedef struct {
            const char *name;
            const char *utf8;
            uint16_t codepoint;
          } FonticoIcon;

          /* Sorted by name, for an icon chosen at runtime rather than compiled
           * in — a name arriving in an MQTT payload, say. Returns NULL when the
           * manifest has no such icon, which is the one honest answer: drawing
           * a codepoint the font has no glyph for is an invisible box.
           *
           * The table lives in whichever translation unit defines
           * FONTICO_ICONS_IMPLEMENTATION before including this file. Exactly
           * one must, or the linker will say so. Nothing else needs to change,
           * and a firmware that only ever uses the #{PREFIX}* defines can skip it
           * entirely and carry no table at all.
           */
          const char *fontico_icon(const char *name);
          extern const FonticoIcon fontico_icons[FONTICO_ICON_COUNT];

          #ifdef FONTICO_ICONS_IMPLEMENTATION
          #include <stdlib.h>
          #include <string.h>

          const FonticoIcon fontico_icons[FONTICO_ICON_COUNT] = {
          #{rows.map { %(  { "#{_1[:name]}", #{_1[:ident]}, 0x#{format("%04X", _1[:codepoint])} },) }.join("\n")}
          };

          static int fontico_icon_cmp(const void *key, const void *el) {
            return strcmp((const char *)key, ((const FonticoIcon *)el)->name);
          }

          const char *fontico_icon(const char *name) {
            const FonticoIcon *hit;
            if (!name) return NULL;
            hit = (const FonticoIcon *)bsearch(name, fontico_icons, FONTICO_ICON_COUNT,
                                               sizeof(FonticoIcon), fontico_icon_cmp);
            return hit ? hit->utf8 : NULL;
          }
          #endif /* FONTICO_ICONS_IMPLEMENTATION */

          #ifdef __cplusplus
          }
          #endif

          #endif /* FONTICO_ICONS_H */
        HEADER
      end

      private

      def row(icon)
        # Never mint one here. The builder has already save!d the lock by the
        # time it emits, so a codepoint invented now would reach the firmware
        # without ever reaching disk — and the font would have no glyph there.
        cp = @lock&.codepoint_for(icon.name)
        raise Fontico::Error, "#{icon.name} has no codepoint in icons.lock" if cp.nil?

        { name: icon.name, ident: self.class.identifier(icon.name),
          codepoint: cp, source: icon.source }
      end

      # The table is sorted here with Ruby's byte-order <=> and searched on the
      # device with strcmp, where `char` is signed on most toolchains. A byte
      # above 0x7F orders one way here and the opposite there, so bsearch would
      # quietly miss the icon rather than fail — an invisible box again.
      def guard_ascii!(rows)
        wide = rows.reject { _1[:name].ascii_only? }
        return if wide.empty?

        raise Fontico::Error,
              "the c target needs ASCII icon names; these are not: " \
              "#{wide.map { _1[:name] }.join(", ")}"
      end

      # ICON_NAV_MENU can be reached from nav.menu and from nav-menu, and C
      # would take the second #define silently. Name both instead.
      def guard_collisions!(rows)
        clashes = rows.group_by { _1[:ident] }.select { |_, v| v.size > 1 }
        return if clashes.empty?

        detail = clashes.map { |ident, group| "#{ident} <- #{group.map { _1[:name] }.join(", ")}" }
        raise Fontico::Error,
              "icon names collide as C identifiers:\n  #{detail.join("\n  ")}\n" \
              "Rename one side in icons.yml; dots, dashes and case all fold to the same macro."
      end

      def defines(rows)
        width = rows.map { _1[:ident].length }.max.to_i
        rows.map do |r|
          format(%(#define %-#{width}s "%s" /* %s  U+%04X */),
                 r[:ident], self.class.utf8_literal(r[:codepoint]), r[:source], r[:codepoint])
        end
      end
    end
  end
end
