# frozen_string_literal: true

module Fontico
  module Emitters
    # The small amount of CSS that makes an <svg> behave like a glyph.
    #
    # Colour is already handled: bodies are folded to `currentColor`, which is
    # what makes an *external* sprite themeable at all — host CSS does not
    # cascade into a cross-document <use>, but inherited properties like
    # `color` do reach it.
    class Stylesheet
      def initialize(manifest, _build)
        @manifest = manifest
      end

      # Contributes no icons, only rules — so the builder must not count all
      # 91 of them as "skipped" on its behalf.
      def accepts?(_icon) = false
      def rules_only?     = true

      def call
        <<~CSS
          /* generated by fontico — do not edit */
          .#{Fontico.css_class} {
            display: inline-block;
            width: 1em;
            height: 1em;

            /* An <svg> sits on the text baseline's bottom edge, a glyph sits
               slightly below it. This is the conventional nudge; tune it if
               your body face has unusual metrics. */
            vertical-align: -0.125em;

            /* Never let a flex or grid parent squash an icon. */
            flex: none;
          }

          /* Optical sizing for icons set beside larger text. */
          .#{Fontico.css_class}-lg { width: 1.25em; height: 1.25em; }
          .#{Fontico.css_class}-xl { width: 1.5em;  height: 1.5em;  }
        CSS
      end
    end
  end
end
